local_costmap:
    global_frame: map
    robot_base_frame: base_link
    update_frequency: 5.0
    publish_frequency: 2.0


    static_map: true
    rolling_window: true
    width: 2.0
    height: 2.0
    resolution: 0.05

    plugins: 
        - {name: static_layer,            type: "costmap_2d::StaticLayer"}
        - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
        - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}

    static_layer:
        enabled:              true
        map_topic:            "/map"


    inflation_layer:
        enabled:              true
        cost_scaling_factor:  3  
        inflation_radius:     2

    obstacle_layer:
        observation_sources: lidar_1
        footprint_clearing_enabled: true
        lidar_1: {data_type: LaserScan, sensor_frame: base_link, clearing: true, marking: true, topic: /scan}
          
